apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: web-browser-researcher
      app.kubernetes.io/managed-by: agent-office
      agentoffice.ai/agent: web-browser-researcher
      backstage.io/kubernetes-id: web-browser-researcher
    includeSelectors: false
resources:
  - agentworkstation.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - networkpolicy.yaml
